/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.BloodBank;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chandrkiran
 */
public class BloodBankArea extends javax.swing.JPanel {
    JPanel userProcessContainer;
    JPanel ViewRequest;
 
    
    private DefaultTableModel bloodBankTableModel;
    private DefaultTableModel bloodRequestTableModel;
    
    
    private String[][] bloodBanks = {
        {"1", "Central Blood Bank", "California"},
        {"2", "EastBlood Bank", "California"}
    };

    // Hardcoded data for Blood Requests
    private String[][] bloodRequests = {
        {"1", "Alice", "A+", "California", "Pending"},
        {"2", "Bob", "B-", "Boston", "Accepted"}
    };
    /**
     * Creates new form BloodBankArea
     */
    

    /**
     * Creates new form BloodBankArea
     */
    public BloodBankArea(JPanel userProcessContainer) {
        this.userProcessContainer = userProcessContainer;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnViewRequest = new javax.swing.JButton();
        btnMngrequest = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        btnViewRequest.setText("View requests");
        btnViewRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewRequestActionPerformed(evt);
            }
        });

        btnMngrequest.setText("manage requst");
        btnMngrequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngrequestActionPerformed(evt);
            }
        });

        jLabel1.setText("Blood Bank work area");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnMngrequest)
                            .addComponent(btnViewRequest)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addComponent(jLabel1)))
                .addContainerGap(240, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(68, 68, 68)
                .addComponent(btnViewRequest)
                .addGap(69, 69, 69)
                .addComponent(btnMngrequest)
                .addContainerGap(282, Short.MAX_VALUE))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewRequestActionPerformed
        // TODO add your handling code here:
        
        
    // Create the BloodBankArea panel
   ViewRequest viewRequestPanel = new ViewRequest(userProcessContainer);

    // Add the panel to the container with a unique card name
    userProcessContainer.add("ViewRequest", viewRequestPanel);

    // Switch to the ViewRequest panel
    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
    layout.show(userProcessContainer, "ViewRequest");
        
        
       
        
    }//GEN-LAST:event_btnViewRequestActionPerformed

    private void btnMngrequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngrequestActionPerformed
        // TODO add your handling code here:
          // Create the BloodBankArea panel
  ManageRequest manageRequest = new ManageRequest(userProcessContainer);

    // Add the panel to the container with a unique card name
    userProcessContainer.add("ViewRequest", manageRequest);

    // Switch to the ViewRequest panel
    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
    layout.show(userProcessContainer, "manageRequest");
        
    }//GEN-LAST:event_btnMngrequestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMngrequest;
    private javax.swing.JButton btnViewRequest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
