/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.BloodBank;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chandrkiran
 */
public class ViewRequest extends javax.swing.JPanel {
    JPanel userProcessContainer;

    /**
     * Creates new form ViewRequest
     */
   

    /**
     * Creates new form ViewRequest
     */
    public ViewRequest(JPanel userProcessContainer) {
        this.userProcessContainer= userProcessContainer;
        
        initComponents();
        populateTable(); 
    }
 private void populateTable() {
        DefaultTableModel tableModel = (DefaultTableModel) tblbloodRequest.getModel();

    // Clear existing rows if any
    tableModel.setRowCount(0);

    // Add dummy data
    Object[][] bloodRequests = {
        {"1", "Alice", "A+", "California", "Pending"},
        {"2", "Bob", "B-", "Boston", "Accepted"},
        {"3", "Charlie", "O+", "California", "Rejected"},
        {"4", "David", "AB-", "Boston", "Pending"}, {"5", "John", "AB-", "Boston", "Pending"}, {"5", "Micheal", "B-", "Boston", "Pending"}, {"7", "Sam", "A/=", "Boston", "Pending"}
    };

    // Populate the table
    for (Object[] request : bloodRequests) {
        tableModel.addRow(request);
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblbloodRequest = new javax.swing.JTable();
        btnAccept = new javax.swing.JButton();
        btnReject = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        tblbloodRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblbloodRequest);

        btnAccept.setText("Accept");
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });

        btnReject.setText("Reject");
        btnReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectActionPerformed(evt);
            }
        });

        jButton1.setText("<<<Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jButton1)
                        .addGap(80, 80, 80)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(337, 337, 337)
                        .addComponent(btnAccept)
                        .addGap(121, 121, 121)
                        .addComponent(btnReject)))
                .addContainerGap(206, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAccept)
                    .addComponent(btnReject))
                .addContainerGap(274, Short.MAX_VALUE))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
        // TODO add your handling code here:
         int selectedRow = tblbloodRequest.getSelectedRow();

    if (selectedRow >= 0) {
        // Update the status to "Accepted"
        DefaultTableModel tableModel = (DefaultTableModel) tblbloodRequest.getModel();
        tableModel.setValueAt("Accepted", selectedRow, 4); // Assuming the status is in the 5th column (index 4)
        JOptionPane.showMessageDialog(this, "Request Accepted!");
    } else {
        JOptionPane.showMessageDialog(this, "Please select a request to accept.");
    }
    }//GEN-LAST:event_btnAcceptActionPerformed

    private void btnRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectActionPerformed
        // TODO add your handling code here:
        
         int selectedRow = tblbloodRequest.getSelectedRow();

    if (selectedRow >= 0) {
        // Update the status to "Rejected"
        DefaultTableModel tableModel = (DefaultTableModel) tblbloodRequest.getModel();
        tableModel.setValueAt("Rejected", selectedRow, 4); // Assuming the status is in the 5th column (index 4)
        JOptionPane.showMessageDialog(this, "Request Rejected!");
    } else {
        JOptionPane.showMessageDialog(this, "Please select a request to reject.");
    }
    }//GEN-LAST:event_btnRejectActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
          userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnReject;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblbloodRequest;
    // End of variables declaration//GEN-END:variables
}
