/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.BloodBankRole;

import Business.BloodBank.BloodBank;
import Business.BloodBank.BloodBankDirectory;
import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.BloodRequestWorkRequest;
import UI.BloodBankRole.ManageBloodBanksPanel;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;

/**
 *
 * @author antaradeshmukh
 */
public class BloodBankWorkAreaPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private BloodBankDirectory bloodBankDirectory;
    private UserAccount userAccount;
    //private List<BloodRequestWorkRequest> requestList = new ArrayList<>();

    /**
     * Creates new form BloodBankWorkAreaPanel
     */
      public BloodBankWorkAreaPanel(JPanel userProcessContainer) {
        this.userProcessContainer = userProcessContainer;
        this.bloodBankDirectory = bloodBankDirectory;
        this.userAccount = userAccount;

        

        initComponents();
    }

//    public BloodBankWorkAreaPanel() {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnViewRequest = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel1.setText("Blood Bank Dashboard");

        btnViewRequest.setText("View Request ");
        btnViewRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewRequestActionPerformed(evt);
            }
        });

        jButton1.setText("Manage ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(374, 374, 374)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(btnViewRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2)
                            .addComponent(jButton1))))
                .addContainerGap(367, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(131, 131, 131)
                .addComponent(btnViewRequest)
                .addGap(59, 59, 59)
                .addComponent(jButton1)
                .addGap(50, 50, 50)
                .addComponent(jButton2)
                .addContainerGap(120, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
//    private void loadRequests() {
//        try {
//            requestList.add(new BloodRequestWorkRequest("1", "A+", "Pending", "2024-12-07"));
//            requestList.add(new BloodRequestWorkRequest("2", "O-", "Pending", "2024-12-06"));
//            requestList.add(new BloodRequestWorkRequest("3", "B+", "Pending", "2024-12-05"));
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
//    }

    private void btnViewRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewRequestActionPerformed
       // Create the ViewRequests panel and pass the userProcessContainer and requestList
    ViewRequests viewRequest = new ViewRequests(userProcessContainer);

    // Remove current panel and add ViewRequests panel
    
    userProcessContainer.add("ViewRequest", viewRequest);

    // Show the ViewRequests panel
    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
    layout.show(userProcessContainer, "ViewRequestPanel");

    System.out.println("Navigated to View Request Panel");
    }//GEN-LAST:event_btnViewRequestActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        ManageBloodBanksPanel manageBloodBanksPanel = new ManageBloodBanksPanel(userProcessContainer, bloodBankDirectory);

        // Remove current panel and add ManageBloodBanksPanel
        userProcessContainer.removeAll();
        userProcessContainer.add("ManageBloodBanksPanel", manageBloodBanksPanel);

        // Show the new panel
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.show(userProcessContainer, "ManageBloodBanksPanel");
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnViewRequest;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
